import type { ColorScheme } from '../types/theme';

export function generateToml(scheme: ColorScheme): string {
  const { core: c, terminal: t, name, description } = scheme;
  return `# ${'='.repeat(76)}
# 🌌 ${name.toUpperCase()}
# ${description}
# Generated by ChromaVoid — https://chromavoid.app
# Style: ${scheme.style}  |  Base Hue: ${scheme.hue}°  |  Seed: ${scheme.seed}
# ${'='.repeat(76)}
# Format: key = "#HEX" (Strict)
# ${'='.repeat(76)}

# CORE UI
background    = "${c.background}"
foreground    = "${c.foreground}"
accent        = "${c.accent}"
accent_bright = "${c.accent_bright}"
cursor        = "${c.cursor}"
selection_bg  = "${c.selection_bg}"
selection_fg  = "${c.selection_fg}"

# TERMINAL PALETTE (ANSI 16)
# ${'─'.repeat(76)}

# DARK SPECTRUM
color0  = "${t.color0}"
color1  = "${t.color1}"
color2  = "${t.color2}"
color3  = "${t.color3}"
color4  = "${t.color4}"
color5  = "${t.color5}"
color6  = "${t.color6}"
color7  = "${t.color7}"

# BRIGHT SPECTRUM
color8  = "${t.color8}"
color9  = "${t.color9}"
color10 = "${t.color10}"
color11 = "${t.color11}"
color12 = "${t.color12}"
color13 = "${t.color13}"
color14 = "${t.color14}"

# 💎 THE IMPROVED COLOR15 (Spectral Silver)
color15 = "${t.color15}"
`;
}

export function downloadToml(scheme: ColorScheme): void {
  const content = generateToml(scheme);
  const blob = new Blob([content], { type: 'text/plain' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = `colors.toml`;
  a.click();
  URL.revokeObjectURL(url);
}
